[theme]
primaryColor = "#C44CD4" # pink-violet button tone
backgroundColor="#140a30" # dark, murky purple
secondaryBackgroundColor="#2a1b5e" # navbar/background strip
textColor="#DEE2F0" # soft cool white